# requires the METALNX_ETC_DIR environment to 
services:
  metalnx:
      image: "metalnx" # 
      container_name: metalnx
      build:
        context: ..
        dockerfile: Dockerfile
      volumes:
        - ${METALNX_ETC_DIR}:/etc/irods-ext
        - /Users/conwaymc/Documents/workspace-niehs-rel/metalnx-niehs-plugins:/opt/irods-ext:ro  
      ports:
        - "8080:8080" 
      networks:
        - irodsnet

networks:
   irodsnet:
    external: true
